# This runs the unit tests for the ELUC use case

name: ELUC Use Case

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./use_cases/eluc
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
    - name: Test PYTHONPATH
      run: printenv PYTHONPATH
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with PyLint
      run: pylint ./*
      - name: Lint with Flake8
      run: flake8
    - name: Run unit tests
      run: python -m unittest

